version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app  # Mount frontend directory as a volume
    # command : npm run start

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    # volumes:
      # - ./backend:/app   # Mount backend directory as a volume
